name: CI

on: [push, pull_request]  # Exécuter la CI sur chaque push et PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Installe les dépendances (si fichier requirements.txt)
          pip install pytest pytest-cov   # Installe pytest et pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-fail-under=80
